jobs:
- name: ci
  plan:
  - aggregate:
    - get: #TODO-replace-with-app
      trigger: true
    - get: #TODO-replace-with-infra
  - task: sync_heroku
    file: #TODO-replace-with-infra /concourse/heroku/heroku_sync.yml
    input_mapping: {source: #TODO-replace-with-app}
    params:
      app_name: ((heroku_app_name))
      heroku_email: ((heroku_email))
      heroku_api_token: ((heroku_api_key))

- name: infra
  plan:
  - aggregate:
    - get: #TODO-replace-with-infra
      trigger: true
  - task: apply
    file: #TODO-replace-with-infra /concourse/terraform/task.yml
    input_mapping: {source: #TODO-replace-with-infra-name}
    params:
      github_token: ((github_token))
      heroku_api_key: ((heroku_api_key))
      command: apply
      directories: |
          terraform

#  The with-state is an output from the apply task. It's a git repo with
#  An updated terraform tfstate file.

  - put: #TODO-replace-with-infra
    params:
      repository: with-state
      rebase: true

resources:

- name: #TODO-replace-with-app
  type: git
  source:
      uri: #TODO-replace-with-app-git-uri
      branch: master
      private_key: ((deploy_key_app))

# Replace with your own repository
- name: #TODO-replace-with-infra
  type: git
  source:
      uri: #TODO-replace-with-infra-git-uri
      branch: master
      private_key: ((deploy_key))
