jobs:
- name: ci
  plan:
  - aggregate:
    - get: pgr301-exam-18-app
      trigger: true
    - get: pgr301-exam-18-infra
  - task: sync_heroku
    file: pgr301-exam-18-infra/concourse/heroku/heroku_sync.yml
    input_mapping: {source: pgr301-exam-18-app}
    params:
      app_name: ((heroku_app_name))
      heroku_email: ((heroku_email))
      heroku_api_token: ((heroku_api_key))

- name: infra
  plan:
  - aggregate:
    - get: pgr301-exam-18-infra
      trigger: true
  - task: apply
    file: pgr301-exam-18-infra/concourse/terraform/task.yml
    input_mapping: {source: pgr301-exam-18-infra}
    params:
      github_token: ((github_token))
      heroku_api_key: ((heroku_api_key))
      statuscake_api_key: ((statuscake_api_key))
      command: apply
      directories: |
          terraform

  - put: pgr301-exam-18-infra
    params:
      repository: with-state
      rebase: true

resources:

- name: pgr301-exam-18-app
  type: git
  source:
      uri: git@github.com:pgr301-exam-atumn-2018-100018/pgr301-exam-18-app.git
      branch: master
      private_key: ((deploy_key_app))

- name: pgr301-exam-18-infra
  type: git
  source:
      uri: git@github.com:pgr301-exam-atumn-2018-100018/pgr301-exam-18-infra.git
      branch: master
      private_key: ((deploy_key))
